import type { TopicConfig } from "../types";

export const TOPICS: TopicConfig[] = [
  {
    slug: "ai-development",
    name: "AI Development",
    description: "New tech, tools, frameworks and libraries for developers",
    keywords: [
      "sdk", "framework", "developer tool", "api", "library", "open source",
      "typescript", "python", "rust", "langchain", "llamaindex", "vector database",
      "hugging face", "transformers", "pytorch", "tensorflow", "mlx",
      "embedding", "tokenizer", "model training", "fine-tuning", "lora",
      "qlora", "quantization", "onnx", "triton", "cuda", "gpu",
      "developer experience", "dx", "devtools", "code generation",
      "copilot", "cursor", "windsurf", "coding assistant",
    ],
    displayOrder: 0,
  },
  {
    slug: "ai-production",
    name: "AI in Production",
    description: "LLMs in production apps — chatbots, agents, RAG, best stacks",
    keywords: [
      "production", "deployment", "rag", "retrieval augmented", "chatbot",
      "agent", "autonomous agent", "multi-agent", "agentic", "tool use",
      "function calling", "guardrails", "evaluation", "eval", "observability",
      "monitoring", "latency", "inference", "serving", "scaling",
      "prompt engineering", "prompt management", "a/b testing",
      "safety", "alignment", "hallucination", "grounding",
      "langsmith", "langfuse", "braintrust", "helicone",
      "vercel ai sdk", "anthropic sdk", "openai api",
      "vector search", "pinecone", "weaviate", "chroma", "qdrant",
    ],
    displayOrder: 1,
  },
  {
    slug: "ai-product-tools",
    name: "AI Product Tools",
    description: "Tools that enhance product team workflows",
    keywords: [
      "product management", "product tool", "productivity", "workflow",
      "no-code", "low-code", "automation", "zapier", "make.com",
      "notion ai", "linear", "figma ai", "design tool",
      "user research", "analytics", "a/b test", "feature flag",
      "project management", "collaboration", "documentation",
      "meeting", "transcription", "summarization tool",
      "writing assistant", "content generation", "marketing ai",
    ],
    displayOrder: 2,
  },
  {
    slug: "ai-research",
    name: "AI Research & Breakthroughs",
    description: "Major papers, model releases, benchmarks",
    keywords: [
      "research paper", "arxiv", "benchmark", "state of the art", "sota",
      "breakthrough", "novel approach", "foundation model", "frontier model",
      "gpt-5", "gpt-4", "claude", "gemini", "llama", "mistral", "qwen",
      "reasoning", "chain of thought", "multimodal", "vision language",
      "diffusion", "image generation", "video generation", "sora",
      "reinforcement learning", "rlhf", "dpo", "constitutional ai",
      "scaling law", "emergent", "capability", "safety research",
      "interpretability", "mechanistic", "alignment research",
    ],
    displayOrder: 3,
  },
  {
    slug: "ai-business",
    name: "AI Business & Industry",
    description: "Funding, acquisitions, regulations, enterprise adoption",
    keywords: [
      "funding", "raised", "investment", "valuation", "acquisition",
      "ipo", "startup", "enterprise", "b2b", "saas",
      "regulation", "policy", "eu ai act", "executive order",
      "copyright", "litigation", "lawsuit", "open source debate",
      "market", "revenue", "growth", "adoption", "survey",
      "openai", "anthropic", "google deepmind", "meta ai", "microsoft",
      "nvidia", "chips", "semiconductor", "data center", "compute",
      "partnership", "deal", "launch", "release", "generally available",
    ],
    displayOrder: 4,
  },
];
